# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "DiscordRichPresence";
    version = "1.2.1.24";
    hash = "sha256-oRNrlF1/yK0QvrW2+48RsmSg9h9/pDIfA56/bpoHXFU=";
  })
  (fetchNuGet {
    pname = "Godot.NET.Sdk";
    version = "4.5.0-beta.1";
    hash = "sha256-uQGzs9+pd3I9s/9RYXDwhQld9IRS8GrOMmfksPDd9/g=";
  })
  (fetchNuGet {
    pname = "Godot.SourceGenerators";
    version = "4.5.0-beta.1";
    hash = "sha256-axXn7a1aA0s+Fcjej1WNEd661HERrsqVKYTeUuLc3U0=";
  })
  (fetchNuGet {
    pname = "GodotSharp";
    version = "4.5.0-beta.1";
    hash = "sha256-V5RePtf0ewzdWdLEHBmzWHTHftwfqpZWzNb5g0M8uFQ=";
  })
  (fetchNuGet {
    pname = "GodotSharpEditor";
    version = "4.5.0-beta.1";
    hash = "sha256-VNYTxC8UI+AtVfU0r9DTdCcqYr+3ZIQ4+yzsNXwlOd0=";
  })
  (fetchNuGet {
    pname = "KeraLua";
    version = "1.4.4";
    hash = "sha256-MF7DBdc8xNiEcauNer7YFRgjbUU4ANmc2uQKrzVDRDs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    hash = "sha256-IEvBk6wUXSdyCnkj6tHahOJv290tVVT8tyemYcR0Yro=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "4.5.0";
    hash = "sha256-WMBXsIb0DgPFPaFkNVxY9b9vcMxPqtgFgijKYMJfV/0=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
  })
  (fetchNuGet {
    pname = "NLua";
    version = "1.7.5";
    hash = "sha256-1s8cc1RqKnfwafhxpBhOdkr8ZteNjt5fBN2sfLy4e5k=";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "4.5.0";
    hash = "sha256-AFsKPb/nTk2/mqH/PYpaoI8PLsiKKimaXf+7Mb5VfPM=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.5.0";
    hash = "sha256-BkUYNguz0e4NJp1kkW7aJBn3dyH9STwB5N8XqnlCsmY=";
  })
]
